services:
  postgres:
    image: postgres:16-alpine
    container_name: maat-postgres
    environment:
      POSTGRES_DB: maat
      POSTGRES_USER: maat
      POSTGRES_PASSWORD: maat
    ports:
      - "14532:5432"
    volumes:
      - maat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maat -d maat"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: maat-mailhog
    ports:
      - "14525:1025"
      - "14580:8025"

  redis:
    image: redis:7-alpine
    container_name: maat-redis
    ports:
      - "14679:6379"

volumes:
  maat_postgres_data:
